server {
    listen 80;
    server_tokens off;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /static/admin/ {
        alias /app/static/admin/;
    }

    location /static/rest_framework/ {
        alias /app/static/rest_framework/;
    }

    location /media/ {
        alias /app/media/;
    }
}