server {
    listen 80;
    server_name foodgramyandexprac.duckdns.org 158.160.211.228;

    location /static/admin/ {
        root /app/;
    }

    location /static/rest_framework/ {
        root /app/;
    }

    location /static/ {
        root /usr/share/nginx/html/;
    }

    location /media/ {
        proxy_set_header Host $host;
        alias  /app/media/;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_set_header Host $host;
        proxy_pass http://backend:8000;
    }

    location /s/ {
         proxy_set_header Host $host;
        proxy_pass http://backend:8000;
    }

    location / {
        root /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}